# Site settings
title: LiVoxGen | LiDAR Voxel Generator
description: "A C++ Program to Voxelize LiDAR Data"
url: "http://megankress.github.io"
author:
  name: "Megan Kress"
  email: "kressmeg@msu.edu"
  url: ""


# Build settings
baseurl: /LiVoxGen/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
